## **Machine Learning**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [ ]:
X_train.shape

(5634, 30)

In [ ]:
X_test.shape

(1409, 30)

In [ ]:
Y_train.shape

(5634,)

In [ ]:
Y_test.shape

(1409,)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_model=RandomForestClassifier(n_estimators=100,random_state=42)

In [ ]:
rf_model.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred=rf_model.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, ..., 1, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy=accuracy_score(Y_test,y_pred)

In [ ]:
accuracy

0.7856635911994322

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm=confusion_matrix(Y_test,y_pred)
cm

array([[902, 107],
       [195, 205]])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.89      0.86      1009
           1       0.66      0.51      0.58       400

    accuracy                           0.79      1409
   macro avg       0.74      0.70      0.72      1409
weighted avg       0.78      0.79      0.78      1409

## **Approach 1 Handle Class Imbalance**

In [ ]:
rf_balanced=RandomForestClassifier(n_estimators=100,random_state=42,class_weight='balanced')

In [ ]:
rf_balanced.fit(X_train,Y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [ ]:
y_pred_bal=rf_balanced.predict(X_test)

In [ ]:
y_pred_bal

array([0, 0, 0, ..., 1, 0, 1])

In [ ]:
accuracy_new=accuracy_score(Y_test,y_pred_bal)
accuracy_new

0.7920511000709723

In [ ]:
cm_balanced=confusion_matrix(Y_test,y_pred_bal)
cm_balanced

array([[907, 102],
       [191, 209]])

In [ ]:
print(classification_report(Y_test,y_pred_bal))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1009
           1       0.67      0.52      0.59       400

    accuracy                           0.79      1409
   macro avg       0.75      0.71      0.72      1409
weighted avg       0.78      0.79      0.78      1409

## **Approach 2 Hyper Paramater Tuning**

In [ ]:
rf_tuned=RandomForestClassifier(n_estimators=300,max_depth=10,random_state=42,class_weight='balanced')

In [ ]:
rf_tuned.fit(X_train,Y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10, n_estimators=300,
                       random_state=42)

In [ ]:
y_pred_tuned=rf_tuned.predict(X_test)

In [ ]:
y_pred_tuned

array([1, 0, 0, ..., 1, 0, 1])

In [ ]:
accuracy_new_tuned=accuracy_score(Y_test,y_pred_tuned)
accuracy_new_tuned

0.7828246983676366

In [ ]:
cm_balanced=confusion_matrix(Y_test,y_pred_tuned)
cm_balanced

array([[804, 205],
       [101, 299]])

In [ ]:
print(classification_report(Y_test,y_pred_tuned))

              precision    recall  f1-score   support

           0       0.89      0.80      0.84      1009
           1       0.59      0.75      0.66       400

    accuracy                           0.78      1409
   macro avg       0.74      0.77      0.75      1409
weighted avg       0.80      0.78      0.79      1409

## **Approach 3 : Feature Importance Anaylysis**

In [ ]:
import pandas as pd
features_importance=pd.DataFrame({'features':X.columns,'Importance':rf_tuned.feature_importances_})
sorted=features_importance.sort_values(by='Importance',ascending=False)
sorted

                                  features  Importance
0                            Tenure Months    0.179069
2                            Total Charges    0.136460
25                       Contract_Two year    0.102861
1                          Monthly Charges    0.093681
6                           Dependents_Yes    0.068517
10            Internet Service_Fiber optic    0.060228
28         Payment Method_Electronic check    0.046732
24                       Contract_One year    0.036682
13                     Online Security_Yes    0.029356
19                        Tech Support_Yes    0.021106
26                   Paperless Billing_Yes    0.018064
5                              Partner_Yes    0.015846
12     Online Security_No internet service    0.014973
18        Tech Support_No internet service    0.014799
22    Streaming Movies_No internet service    0.014360
16   Device Protection_No internet service    0.012985
11                     Internet Service_No    0.012673
3                              Gender_Male    0.012586
15                       Online Backup_Yes    0.012213
9                       Multiple Lines_Yes    0.011690
14       Online Backup_No internet service    0.010298
4                       Senior Citizen_Yes    0.010257
20        Streaming TV_No internet service    0.010186
23                    Streaming Movies_Yes    0.010161
27  Payment Method_Credit card (automatic)    0.009430
21                        Streaming TV_Yes    0.009289
17                   Device Protection_Yes    0.009101
29             Payment Method_Mailed check    0.008800
7                        Phone Service_Yes    0.003872
8          Multiple Lines_No phone service    0.003725

In [ ]:
X_selected=X.drop(['Phone Service_Yes','Multiple Lines_No phone service',],axis=1)

In [ ]:
X_selected_train,X_selected_test,Y_train_sel,Y_test_sel=train_test_split(X_selected,Y,test_size=0.2,random_state=42)

In [ ]:
rf_selected=RandomForestClassifier(n_estimators=300,max_depth=10,random_state=42,class_weight='balanced')
rf_selected.fit(X_selected_train,Y_train_sel)

RandomForestClassifier(class_weight='balanced', max_depth=10, n_estimators=300,
                       random_state=42)

In [ ]:
y_pred_sel=rf_selected.predict(X_selected_test)

In [ ]:
print(classification_report(Y_test_sel,y_pred_sel))

              precision    recall  f1-score   support

           0       0.89      0.80      0.84      1009
           1       0.60      0.74      0.66       400

    accuracy                           0.78      1409
   macro avg       0.74      0.77      0.75      1409
weighted avg       0.80      0.78      0.79      1409

## **N_estimators and Depth Combinations**

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

In [ ]:
max_depth_lst=[5,10,15,20]
n_estimators_lst=[100,200,300,400,500]
results=[]
for depth in max_depth_lst:
    for n_estimators in n_estimators_lst:
        rf=RandomForestClassifier(n_estimators=n_estimators,max_depth=depth,random_state=42,class_weight='balanced')
        rf.fit(X_train,Y_train)
        y_pred=rf.predict(X_test)
        accuracy=accuracy_score(Y_test,y_pred)
        recall=recall_score(Y_test,y_pred)
        precision=precision_score(Y_test,y_pred)
        f1=f1_score(Y_test,y_pred)
        results.append({"Trees":n_estimators,"Depth":depth,"Accuracy":accuracy,"Recall":recall,"Precision":precision,"F1":f1})
res=pd.DataFrame(results)
res=res.sort_values(by=['Recall','Accuracy'],ascending=False)
res

    Trees  Depth  Accuracy  Recall  Precision        F1
0     100      5  0.745919  0.8200   0.534202  0.646943
2     300      5  0.743790  0.8200   0.531605  0.645034
3     400      5  0.743790  0.8125   0.531915  0.642928
1     200      5  0.742370  0.8100   0.530278  0.640950
4     500      5  0.740951  0.8050   0.528736  0.638256
5     100     10  0.775727  0.7525   0.581081  0.655773
7     300     10  0.782825  0.7475   0.593254  0.661504
8     400     10  0.782825  0.7475   0.593254  0.661504
9     500     10  0.781405  0.7475   0.590909  0.660044
6     200     10  0.782115  0.7450   0.592445  0.660022
12    300     15  0.806246  0.6400   0.664935  0.652229
13    400     15  0.803407  0.6375   0.658915  0.648030
14    500     15  0.801987  0.6375   0.655527  0.646388
11    200     15  0.804826  0.6350   0.663185  0.648787
10    100     15  0.802697  0.6300   0.659686  0.644501
15    100     20  0.787793  0.5325   0.655385  0.587586
16    200     20  0.793471  0.5275   0.674121  0.591865
17    300     20  0.787793  0.5250   0.658307  0.584145
18    400     20  0.786373  0.5225   0.655172  0.581363
19    500     20  0.787793  0.5200   0.660317  0.581818

**Cross Validation**

In [ ]:
from sklearn.model_selection import cross_val_score
final_model=RandomForestClassifier(n_estimators=300,max_depth=10,random_state=42,class_weight='balanced')
scores=cross_val_score(final_model,X,Y,cv=5,scoring='accuracy')
scores

array([0.76721079, 0.79772889, 0.76224273, 0.78551136, 0.78409091])

In [ ]:
scores.mean()

np.float64(0.7793569343183432)

In [ ]:
scores1=cross_val_score(final_model,X,Y,cv=5,scoring='recall')

In [ ]:
scores1.mean()

np.float64(0.7335350030823931)

In [ ]:
from sklearn.metrics import roc_auc_score,roc_curve

In [ ]:
y_prob=rf_selected.predict_proba(X_selected_test)

In [ ]:
churn_proba=y_prob[:,1]
fpr,tpr,threshold=roc_curve(Y_test,churn_proba)
aoc_score=roc_auc_score(Y_test,churn_proba)
print(aoc_score)
print(churn_proba)

0.8570676412289395
[0.71492307 0.32134306 0.25230247 ... 0.73541778 0.07141633 0.77408427]